apiVersion: apps/v1
kind: Deployment
metadata:
  name: sipasta-backend
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sipasta-backend
  template:
    metadata:
      labels:
        app: sipasta-backend
    spec:
      containers:
        - name: sipasta-backend
          image: hori75/sipasta-backend:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URL
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: FIREBASE_PRIVATE_KEY
                  name: backend-secret
          envFrom:
            - configMapRef:
                name: sipasta-backend
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /ping
              port: http
          resources:
            limits:
              memory: 512Mi
              cpu: 250m
            requests:
              memory: 256Mi
              cpu: 125m