resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

configMapGenerator:
  - name: sipasta-backend
    literals:
      - FRONTEND_URL=sipasta.rpksus.xyz
      - FIREBASE_PROJECT_ID=sipasta
      - FIREBASE_CLIENT_EMAIL=firebase-adminsdk-km6f9@sipasta.iam.gserviceaccount.com
    